#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "/Users/advayrajguru/Documents/My Documents/University/University of British Columbia/Year 4/W2/CPSC427/team-01/"
